import 'package:flutter/material.dart';
import 'workflow_data.dart';

final List<WorkflowNodeData> initialNodes = [
  // PART 1
  WorkflowNodeData(
    id: 'Part1Group',
    type: NodeType.group,
    title: 'Part A: Upstream Digital Pipeline · Data → Blueprint',
    label: 'Part A: Upstream Digital Pipeline · Data → Blueprint',
    color: 'indigo',
  ),
  WorkflowNodeData(
    id: 'Title1',
    type: NodeType.title,
    title: 'Part A: Upstream Digital Pipeline',
    description: 'Data → Blueprint',
    parentNode: 'Part1Group',
    color: 'indigo',
  ),
  WorkflowNodeData(
    id: 'NodeIn1A',
    type: NodeType.data,
    title: 'Patient tumor biopsy sample',
    description: '',
    parentNode: 'Part1Group',
    color: 'blue',
    images: [
      'lib/assets/icons/icon_tissue.png'
    ],
    isHighlighted: false,
  ),
  WorkflowNodeData(
    id: 'NodeIn1B',
    type: NodeType.data,
    title: 'Patient normal blood sample',
    description: '',
    parentNode: 'Part1Group',
    color: 'blue',
    images: [
      'lib/assets/icons/icon_blood.png',
    ],
    isHighlighted: false,
  ),
  WorkflowNodeData(
    id: 'Step1',
    type: NodeType.step,
    title: 'Step 1 · Reading the Blueprint',
    goal: 'Digitizing the Cells',
    description: 'The machine reads extracted DNA/RNA, turning biological chemistry into digital text.',
    hardware: 'Illumina NextSeq 2000 or Element AVITI',
    outsourced: 'Novogene, Azenta, Eurofins',
    cost: '~\$1,000 / pt (In-House) or ~\$2,500 (Outsourced)',
    parentNode: 'Part1Group',
    color: 'rose',
    iconName: 'database',
    image: 'lib/assets/hardware/illumina_nextseq.png',
    inputs: ['Tumor biopsy', 'Normal blood (healthy baseline)'],
    outputs: [
      'baseline-normal.fastq — Normal blood WES (~30X–50X)',
      'tumor-exome.fastq — Tumor biopsy WES (~100X–500X)',
      'tumor-rna.fastq — Tumor biopsy RNA-Seq (~50M–100M reads)',
      'patient-hla.txt — Patient HLA profile (MHC Class I & II typing)'
    ],
    fileFormat: '.fastq & .txt',
  ),
  WorkflowNodeData(
    id: 'NodeIn2',
    type: NodeType.data,
    title: '📄 Genetic files from patient samples',
    description: '1. baseline-normal.fastq — Normal blood WES (~30X–50X)<br/>2. tumor-exome.fastq — Tumor biopsy WES (~100X–500X)<br/>3. tumor-rna.fastq — Tumor biopsy RNA-Seq (~50M–100M reads)<br/>4. patient-hla.txt — Patient HLA profile (MHC Class I & II typing)',
    parentNode: 'Part1Group',
    color: 'blue',
  ),
  WorkflowNodeData(
    id: 'NodeRef',
    type: NodeType.data,
    title: '🧬 Human Reference Genome (.fasta)',
    description: '(e.g. Human Genome Project)<br/>>chr1 NNNNNNNNNN...',
    parentNode: 'Part1Group',
    color: 'slate',
  ),
  WorkflowNodeData(
    id: 'Step2',
    type: NodeType.step,
    title: 'Step 2 · Spotting the Typos',
    goal: 'Finding the Mutations',
    description: 'Aligns reads and mathematically subtracts healthy DNA from tumor DNA to isolate somatic mutations.',
    hardware: 'None',
    software: 'GATK Mutect2',
    parentNode: 'Part1Group',
    color: 'rose',
    iconName: 'zap',
    image: 'lib/assets/icons/icon_ai_script.png',
    inputs: ['3 patient .fastq files', 'Human Reference Genome (.fasta)'],
    outputs: [
      'somatic-variants.vcf — All raw mutation candidates',
      'filtered-variants.vcf — High-confidence, tumor-only mutations'
    ],
    fileFormat: '.vcf',
  ),
  WorkflowNodeData(
    id: 'NodeIn3',
    type: NodeType.data,
    title: '📄 2 Condensed mutation lists (.vcf)',
    description: 'somatic-variants.vcf<br/>filtered-variants.vcf',
    parentNode: 'Part1Group',
    color: 'blue',
  ),
  WorkflowNodeData(
    id: 'NodeHLA',
    type: NodeType.data,
    title: '🔬 Patient HLA profile (.txt)',
    description: 'Immune system receptor map<br/>HLA-A*02:01, HLA-B*07:02...',
    parentNode: 'Part1Group',
    color: 'blue',
  ),
  WorkflowNodeData(
    id: 'Step3',
    type: NodeType.step,
    title: 'Step 3 · Picking the Targets',
    goal: 'AI Neoantigen Prediction',
    description: 'Neural networks predict which mutations will most effectively trigger an immune response based on the patient HLA receptors.',
    hardware: 'None',
    software: 'pVACseq running MHCflurry',
    parentNode: 'Part1Group',
    color: 'rose',
    iconName: 'target',
    image: 'lib/assets/icons/icon_ai_script.png',
    inputs: ['filtered-variants.vcf', 'Patient HLA profile (.txt)'],
    outputs: ['ranked-predictions.tsv — Leaderboard of best targets'],
    fileFormat: '.tsv',
  ),
  WorkflowNodeData(
    id: 'NodeIn4',
    type: NodeType.data,
    title: '📊 Ranked leaderboard of targets (.tsv)',
    description: 'ranked-predictions.tsv<br/>Top predicted neoantigens',
    parentNode: 'Part1Group',
    color: 'blue',
  ),
  WorkflowNodeData(
    id: 'Step4',
    type: NodeType.step,
    title: 'Step 4 · Writing the New Code',
    goal: 'Sequence Assembly',
    description: 'Strings targets together, adds structural instructions (5 Cap, Poly-A tail), and optimizes codons for stability.',
    hardware: 'None',
    software: 'pVACvector + LinearDesign',
    parentNode: 'Part1Group',
    color: 'rose',
    iconName: 'pen-tool',
    image: 'lib/assets/icons/icon_ai_script.png',
    inputs: ['Top targets from ranked-predictions.tsv'],
    outputs: ['vaccine-construct.fasta — Master mRNA sequence'],
    fileFormat: '.fasta',
  ),
  WorkflowNodeData(
    id: 'NodeIn5',
    type: NodeType.data,
    title: '📜 Optimized mRNA blueprint (.fasta)',
    description: 'vaccine-construct.fasta (Master sequence)',
    parentNode: 'Part1Group',
    color: 'blue',
  ),

  // PART 2
  WorkflowNodeData(
    id: 'Part2Group',
    type: NodeType.group,
    title: 'Part B: Downstream Physical Pipeline · Blueprint → Vial',
    label: 'Part B: Downstream Physical Pipeline · Blueprint → Vial',
    color: 'teal',
  ),
  WorkflowNodeData(
    id: 'Title2',
    type: NodeType.title,
    title: 'Part B: Downstream Physical Pipeline',
    description: 'Blueprint → Vial',
    parentNode: 'Part2Group',
    color: 'teal',
  ),
  WorkflowNodeData(
    id: 'Step5',
    type: NodeType.step,
    title: 'Step 5 · Printing the Master Copy',
    goal: 'DNA Synthesis',
    description: 'Gibson Assembly stitches oligonucleotides into a DNA plasmid, which is then linearized with enzymes.',
    hardware: 'Benchtop DNA Synthesizer (e.g., BioXp)',
    outsourced: 'Twist, IDT, GenScript, Azenta',
    cost: '~\$600 / rxn (In-House) or ~\$200-\$900 (Outsourced)',
    parentNode: 'Part2Group',
    color: 'teal',
    iconName: 'printer',
    image: 'lib/assets/hardware/bioxp.jpeg',
    inputs: ['vaccine-construct.fasta blueprint'],
    outputs: ['~1.5 mL Purified linear DNA template (~75 µg)'],
    fileFormat: 'Liquid DNA',
  ),
  WorkflowNodeData(
    id: 'NodeIn6',
    type: NodeType.data,
    title: '📜 1.5 mL Purified linear DNA template',
    description: 'Yield: ~75 µg (at ~50 ng/µL)<br/>Stable at -20°C',
    parentNode: 'Part2Group',
    color: 'teal',
    images: ['lib/assets/icons/icon_dna.png'],
  ),
  WorkflowNodeData(
    id: 'NodeIVT',
    type: NodeType.data,
    title: '⚗️ IVT Reagents',
    description: 'RNA Polymerase, N1-methylpseudouridine, CleanCap® AG',
    parentNode: 'Part2Group',
    color: 'teal',
  ),
  WorkflowNodeData(
    id: 'Step6',
    type: NodeType.step,
    title: 'Step 6 · Mass Production',
    goal: 'Automated mRNA Synthesis',
    description: 'In Vitro Transcription (IVT) bioreactors read the DNA and print the corresponding mRNA strand.',
    hardware: 'NTxscribe System / BioXp',
    outsourced: 'TriLink, GenScript, BiCell Scientific',
    cost: '~\$2,000 / rxn (In-House) or ~\$1,000-\$3,000 / mg',
    parentNode: 'Part2Group',
    color: 'teal',
    iconName: 'factory',
    image: 'lib/assets/hardware/bioxp.jpeg',
    inputs: ['Linear DNA template', 'IVT Reagents'],
    outputs: ['~5.0 mL Highly pure mRNA (~1.0 mg)'],
    fileFormat: 'Liquid mRNA',
  ),
  WorkflowNodeData(
    id: 'NodeIn7',
    type: NodeType.data,
    title: '💉 5.0 mL Highly pure mRNA',
    description: 'Yield: ~1.0 mg (at ~200 ng/µL)<br/>Stored at -80°C',
    parentNode: 'Part2Group',
    color: 'teal',
    images: ['lib/assets/icons/icon_5ml_dna.png'],
  ),
  WorkflowNodeData(
    id: 'NodeLipids',
    type: NodeType.data,
    title: '🧴 4-Lipid Cocktail',
    description: 'ALC-0315, PEG-Lipid, DSPC, Cholesterol',
    parentNode: 'Part2Group',
    color: 'teal',
  ),
  WorkflowNodeData(
    id: 'Step7',
    type: NodeType.step,
    title: 'Step 7 · Packaging for Delivery',
    goal: 'LNP Formulation',
    description: 'Microfluidic collisions force mRNA and lipids to self-assemble into nanoparticles.',
    hardware: 'Sunshine / NanoAssemblr Ignite',
    outsourced: 'VectorBuilder, Lonza, Vernal Biosciences',
    cost: '~\$500 / rxn (In-House) or ~\$2,000-\$5,000 / batch',
    parentNode: 'Part2Group',
    color: 'teal',
    iconName: 'package',
    image: 'lib/assets/hardware/unchained_sunshine.png',
    inputs: ['Purified mRNA', '4-Lipid Cocktail'],
    outputs: ['~12 mL Raw mRNA-LNP mixture (~0.9 mg encapsulated)'],
    fileFormat: 'LNP Mixture',
  ),
  WorkflowNodeData(
    id: 'NodeIn8',
    type: NodeType.data,
    title: '🧪 12 mL Raw mRNA-LNP mixture',
    description: 'Yield: ~0.9 mg encapsulated (>90% efficiency)<br/>Opalescent liquid',
    parentNode: 'Part2Group',
    color: 'teal',
    images: ['lib/assets/icons/icon_12ml.png'],
  ),
  WorkflowNodeData(
    id: 'Step8',
    type: NodeType.step,
    title: 'Step 8 · Quality Check & Bottling',
    goal: 'QC & Finalization',
    description: 'DLS verifies 60-100nm particles and TFF washes out ethanol.',
    hardware: 'Stunner & TFF System',
    outsourced: 'CordenPharma, uBriGene, VectorBuilder',
    cost: '~\$100 / rxn (In-House) or ~\$1,000-\$3,000 / batch',
    parentNode: 'Part2Group',
    color: 'teal',
    iconName: 'flask-conical',
    image: 'lib/assets/hardware/unchained_stunner.jpeg',
    inputs: ['Raw mRNA-LNP mixture'],
    outputs: ['10 x 1.0 mL sterile glass vials (approx. 10 doses)'],
    fileFormat: 'Final Vaccine Product',
  ),
  WorkflowNodeData(
    id: 'NodeEnd',
    type: NodeType.data,
    title: '💊 10 x 1.0 mL Vaccine Vials',
    description: 'Concentration: ~100 µg/mL<br/>10 Doses ready for clinic',
    parentNode: 'Part2Group',
    color: 'teal',
    images: ['lib/assets/icons/icon_vaccine.png'],
    isHighlighted: false,
  ),
];

final List<WorkflowEdgeData> initialEdges = [
  WorkflowEdgeData(id: 'e1a-step1', source: 'NodeIn1A', target: 'Step1', animated: true),
  WorkflowEdgeData(id: 'e1b-step1', source: 'NodeIn1B', target: 'Step1', animated: true),
  WorkflowEdgeData(id: 'step1-e2', source: 'Step1', target: 'NodeIn2', animated: true),
  WorkflowEdgeData(id: 'e2-step2', source: 'NodeIn2', target: 'Step2', animated: true),
  WorkflowEdgeData(id: 'ref-step2', source: 'NodeRef', target: 'Step2', dashed: true, label: 'Reference'),
  WorkflowEdgeData(id: 'step2-e3', source: 'Step2', target: 'NodeIn3', animated: true),
  WorkflowEdgeData(id: 'hla-step3', source: 'NodeHLA', target: 'Step3', dashed: true),
  WorkflowEdgeData(id: 'e3-step3', source: 'NodeIn3', target: 'Step3', animated: true),
  WorkflowEdgeData(id: 'step3-e4', source: 'Step3', target: 'NodeIn4', animated: true),
  WorkflowEdgeData(id: 'e4-step4', source: 'NodeIn4', target: 'Step4', animated: true),
  WorkflowEdgeData(id: 'step4-e5', source: 'Step4', target: 'NodeIn5', animated: true),
  WorkflowEdgeData(id: 'e5-step5', source: 'NodeIn5', target: 'Step5', animated: true),
  WorkflowEdgeData(id: 'step5-e6', source: 'Step5', target: 'NodeIn6', animated: true),
  WorkflowEdgeData(id: 'ivt-step6', source: 'NodeIVT', target: 'Step6', dashed: true),
  WorkflowEdgeData(id: 'e6-step6', source: 'NodeIn6', target: 'Step6', animated: true),
  WorkflowEdgeData(id: 'step6-e7', source: 'Step6', target: 'NodeIn7', animated: true),
  WorkflowEdgeData(id: 'lipids-step7', source: 'NodeLipids', target: 'Step7', dashed: true),
  WorkflowEdgeData(id: 'e7-step7', source: 'NodeIn7', target: 'Step7', animated: true),
  WorkflowEdgeData(id: 'step7-e8', source: 'Step7', target: 'NodeIn8', animated: true),
  WorkflowEdgeData(id: 'e8-step8', source: 'NodeIn8', target: 'Step8', animated: true),
  WorkflowEdgeData(id: 'step8-end', source: 'Step8', target: 'NodeEnd', animated: true),
];

final List<WorkflowStep> workflowSteps = [
  WorkflowStep(id: 1, title: 'Patient Samples', part: 'Part A: Upstream Digital Pipeline', nodeIds: ['NodeIn1A', 'NodeIn1B']),
  WorkflowStep(id: 2, title: 'Step 1: Reading the Blueprint', part: 'Part A: Upstream Digital Pipeline', nodeIds: ['Step1', 'NodeIn1A', 'NodeIn1B', 'NodeIn2']),
  WorkflowStep(id: 3, title: 'Step 2: Spotting the Typos', part: 'Part A: Upstream Digital Pipeline', nodeIds: ['Step2', 'NodeIn2', 'NodeRef', 'NodeIn3']),
  WorkflowStep(id: 4, title: 'Step 3: Picking the Targets', part: 'Part A: Upstream Digital Pipeline', nodeIds: ['Step3', 'NodeIn3', 'NodeHLA', 'NodeIn4']),
  WorkflowStep(id: 5, title: 'Step 4: Writing the New Code', part: 'Part A: Upstream Digital Pipeline', nodeIds: ['Step4', 'NodeIn4', 'NodeIn5']),
  WorkflowStep(id: 6, title: 'Step 5: Printing the Master Copy', part: 'Part B: Downstream Physical Pipeline', nodeIds: ['Step5', 'NodeIn5', 'NodeIn6']),
  WorkflowStep(id: 7, title: 'Step 6: Mass Production', part: 'Part B: Downstream Physical Pipeline', nodeIds: ['Step6', 'NodeIn6', 'NodeIVT', 'NodeIn7']),
  WorkflowStep(id: 8, title: 'Step 7: Packaging for Delivery', part: 'Part B: Downstream Physical Pipeline', nodeIds: ['Step7', 'NodeIn7', 'NodeLipids', 'NodeIn8']),
  WorkflowStep(id: 9, title: 'Step 8: Quality Check & Bottling', part: 'Part B: Downstream Physical Pipeline', nodeIds: ['Step8', 'NodeIn8', 'NodeEnd']),
  WorkflowStep(id: 10, title: 'Final Vaccine Product', part: 'Part B: Downstream Physical Pipeline', nodeIds: ['NodeEnd']),
];
